### ISSUE TITLE
The way you calculate mAP is wrong

### ISSUE THREAD

**Issue by suanrong** [chenzhaomin123/ML_GCN#8]
you should calculate AP among each sample, rather than each class.

**Comment by chenzhaomin123** [comment]
As far as we know, all multi label task calculate AP among each class. This project is based https://github.com/durandtibo/wildcat.pytorch. You can see SRN or Wildcat to verify mAP.

**Comment by suanrong** [comment]
According to 
https://www.researchgate.net/publication/327110772_A_Survey_on_Multi_Label_Classification  
&
https://pdfs.semanticscholar.org/6b56/91db1e3a79af5e3c136d2dd322016a687a0b.pdf

AP should be calculated among samples. It is a classification task, not a retrieval task.

**Comment by chenzhaomin123** [comment]
According to
[http://openaccess.thecvf.com/content_ICCV_2017/papers/Wang_Multi-Label_Image_Recognition_ICCV_2017_paper.pdf](url)
&
[http://openaccess.thecvf.com/content_cvpr_2017/papers/Zhu_Learning_Spatial_Regularization_CVPR_2017_paper.pdf](url)
&
[http://openaccess.thecvf.com/content_cvpr_2017/papers/Durand_WILDCAT_Weakly_Supervised_CVPR_2017_paper.pdf](url)

mAP was calculated as multiple image retrieval tasks.  The three listed papers are published on ICCV or CVPR respectively and **in our paper, we have pointed out that we follow this setting.**

There are many methods to calculate mAP, but for fair comparison, we should calculate mAP among each class.

You can see [https://github.com/zhufengx/SRN_multilabel/issues/5](url) for more detail.

**Comment by chenzhaomin123** [comment]
In addition, we do think your proposed method to calculate mAP is interesting and we would be more than happy to update the result if the experiment results for the above methods using your proposed method can be provided.

**Comment by suanrong** [comment]
Thank you for your reply~

**Comment by Abhinav43** [comment]
@chenzhaomin123 , Your code is working and everything good, I was going through your paper for theoretical information,  In your paper you said you "A directed graph is built over these label
representations, where each node denotes a label." 

I am confuse how you are building directed graph? If I am getting right then :

Directed graph is another name of correlation matrix or adjacency matrix ?

But then how this adjacency matrix / correlation matrix is directed graph because we can go from label a to label b and also label b to label a ?

Thanks for quick replies :)
